require_relative 'evolve/gene'
require_relative 'evolve/species'
require_relative 'evolve/population'
require_relative 'evolve/evolution/strategy'
require_relative 'evolve/evolution/runner'
require_relative 'evolve/evolution/configuration'
