require_relative 'evolve/evolution/operators/base'
require_relative 'evolve/evolution/operators/selection'
require_relative 'evolve/evolution/operators/reproduction'
require_relative 'evolve/evolution/operators/mutation'

require_relative 'evolve/gene'
require_relative 'evolve/species'
require_relative 'evolve/population'
require_relative 'evolve/evolution/strategy'
require_relative 'evolve/evolution/runner'
require_relative 'evolve/evolution/configuration'
